# helper functions

# Determine the filenames of the data sources.
# @return A character vector with filenames
getDataFiles <- function() {
  row <- which( ( options[ , 'Design'] == input$dsg &
                    options[ , 'Location'] == input$loc &
                    options[ , 'Material'] == input$mat &
                    options[ , 'Analysis'] == input$ana ) )
  if( row < 1) {
    showNotification( 'No data found. (Check file with available options?) Error code #1.', type = 'error')
    return( NULL)
  }
  ## fixme: trengs Subfile?
  files <- as.vector( unname( unlist( options[ row, c( 'File1', 'File2', 'File3') ] ) ) )
  files <- files[ files != '']
  areReadable = ( file.access( files, 4) > -1)
  if( sum( areReadable) != length( areReadable) ) {
    showNotification( 'Data source not readable. (Check file with available options?) Error code #2.', type = 'error')
    return( NULL)
  }
  return( files)
} # function getDataFiles

# Format a code line as a comment.
# @param string: Code line
# @return string
cmt <- function( line) {
  paste( "#'", line)
}

# Wrap a string in quotes.
# @param string
# @return string
wrapInQuotes <- function( string) {
  paste0( '"', string, '"')
}

# Create a list object to store the attributes of a processing step.
# @param string: step label
# @param boolean: true if step is enabled, false otherwise
# @param character vector: code line strings
# @return list
createStep <- function( label, enabled = FALSE, code = c() ) {
  list( label = label, enabled = enabled, code = code)
}

# Generate the documentation for all processing steps.
# @param list object with processing pipeline attributes
# @return character vector: code lines
documentSteps <- function( pipeline) {
  doc <- c()
  for( step in pipeline$steps) {
    if( step$enabled) {
      doc <- c(
        doc,
        '',
        cmt( step$label),
        step$code
      )
    }
  }
  return( doc)
} # function documentSteps

# Write the code that instantiates both the processing and documentation of a processing pipeline.
# @param string: filename to write the code to
# @param list object with pipeline attributes
documentPipeline <- function( filename, pipeline) {
  doc <- c(
    ## YAML
    cmt( '---'),
    cmt( paste( 'title:', wrapInQuotes( pipeline$basics$title) ) ),
    cmt( paste( 'author:', wrapInQuotes( pipeline$choices$author) ) ),
    cmt( paste( 'date:', wrapInQuotes( Sys.time() ) ) ),
    cmt( '---'),
    ## header
    cmt( ''),
    cmt( 'This document describes how the associated biobank dataset was prepared.'),
    cmt( paste0( 'It was generated by ', pipeline$basics$appName, ', version ', pipeline$basics$appVersion, '.') ),
    cmt( ''),
    cmt( 'Start of pipeline'),
    ## processing, incl. read and write
    documentSteps( pipeline),
    ## footer
    '',
    cmt( 'End of pipeline')
  )
  writeLines( doc, filename)
} # function documentPipeline

